// <auto-generated />
using System;
using KFH;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KFH.Migrations
{
    [DbContext(typeof(KFHContext))]
    partial class KFHContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KFH.CustomerAccount", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountNumber"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AccountNumber");

                    b.ToTable("CustomerAccounts");
                });

            modelBuilder.Entity("KFH.TransferRequest", b =>
                {
                    b.Property<int>("SourceAccount")
                        .HasColumnType("int");

                    b.Property<int>("DestinationAccount")
                        .HasColumnType("int");

                    b.Property<int>("CreatedDate")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SourceAccount", "DestinationAccount", "CreatedDate");

                    b.HasIndex("DestinationAccount");

                    b.ToTable("TransferRequests");
                });

            modelBuilder.Entity("KFH.TransferRequest", b =>
                {
                    b.HasOne("KFH.CustomerAccount", null)
                        .WithMany()
                        .HasForeignKey("DestinationAccount")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KFH.CustomerAccount", null)
                        .WithMany()
                        .HasForeignKey("SourceAccount")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
